language: node_js

node_js:
  - '0.10'

before_install:
  - npm install -g bower
  - npm install -g gulp

install:
  - npm install
  - bower install --config.interactive=false
  - gulp build --prod

script:
  - gulp test

